version: "3.9"

services:
  frontend:
    image: ikcap/disk_frontend
    ports:
      - 8000:80
    restart: on-failure:5
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
  backend:
    image: ikcap/disk_backend
    ports:
      - 8080:8080
    restart: on-failure:5
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./server.properties:/root/.disk/server.properties
      - disk-storage:/root/.disk/storage
  endpoint:
    image: ikcap/fuseki_docker
    ports:
      - 3030:3030
    volumes:
      - fuseki_backups:/backups
      - fuseki_databases:/fuseki-base/databases/
    env_file:
      - .env
    restart: on-failure:5
  wings:
    image: "ikcap/wings:5.2.0"
    environment:
      WINGS_MODE: dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - wings:/opt/wings
    ports:
      - 7080:8080
    restart: on-failure:5
volumes:
  mysql:
  fuseki_databases:
  fuseki_backups:
  wings:
  disk-storage:
