version: '3.9'

services:
  frontend:
    image: ikcap/disk_frontend:latest
    ports:
      - '8080:80'
  backend:
    image: ikcap/disk_backend:latest
    ports:
      - '8080'
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml