version: '3.9'

services:
  frontend:
    image: ikcap/disk_frontend:docker
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - '8080:80' 
    volumes:
      - ./docker/frontend/config.js:/usr/share/nginx/html/disk-portal/customize/config.js
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: ikcap/disk_backend:docker
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - '8080'
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./server.properties:$HOME/.disk/server.properties