version: '3.9'

services:
  frontend:
    image: ikcap/disk_frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - '8080:80' 
    volumes:
      - ./config.js:/usr/share/nginx/html/disk-portal/customize/config.js
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: ikcap/disk_backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - '8080'
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./server.properties:/root/.disk/server.properties
      - disk-storage:/root/.disk/storage
  endpoint:
    image: ikcap/fuseki_docker
    ports:
      - 3030:3030
    volumes:
      - fuseki_backups:/backups
      - fuseki_databases:/fuseki-base/databases/
    env_file:
      - .env
  wings:
    image: "ikcap/wings:4.2.6"
    environment:
      WINGS_MODE: dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - wings:/opt/wings
    ports:
      - 7080:8080
volumes:
  mysql:
  fuseki_databases:
  fuseki_backups:
  wings:
  disk-storage:
