version: '3.9'

services:
  frontend:
    image: ikcap/disk_frontend:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - '8080:80' 
    volumes:
      - ./config.js:/usr/share/nginx/html/disk-portal/customize/config.js
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: ikcap/disk_backend:latest
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - '8080'
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./server.properties:/root/.disk/server.properties
  database:
    image: ikcap/disk_database
    restart: always
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
  mediawiki:
    image: ikcap/disk_wiki
    env_file:
      - .env
    restart: always
    ports:
      - 9080:80
    depends_on:
      - database
  endpoint:
    image: ikcap/fuseki_docker
    ports:
      - 3030:3030
    volumes:
      - fuseki_backups:/backups
      - fuseki_databases:/fuseki-base/databases/
    env_file:
      - .env
  wings:
    image: "kcapd/wings-base:latest"
    environment:
      WINGS_MODE: dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7080:8080
volumes:
  mysql:
  fuseki_databases:
  fuseki_backups:
  wings: