package org.diskproject.shared.classes.workflow;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

public class VariableBinding implements Serializable, Comparable<VariableBinding> {
  private static final long serialVersionUID = -847994634505985728L;

  public static enum BindingTypes {
    // Inputs:
    DEFAULT,            // The default value, for workflows means to use the workflow default value.
    FREEFORM,           // The binding was written directly by the user.
    DATA_QUERY,         // The binding is the complete data query as a CSV.
    QUERY_VARIABLE,     // The binding is a variable to get from the data-query.
    WORKFLOW_VARIABLE,  // The binding is a output variable from a previously executed workflow.
    DISK_DATA,          // The binding is metadata generated by DISK.
    // Outputs:
    DROP,     // Do no save
    SAVE,     // Save on DISK
    PROCESS   // Use the file to do post processing
  }
  
  String variable;        // Variable NAME
  List<String> binding;   // Binding VALUE
  boolean isArray;        // This binding is an array, if false bindings list will only have one value.
  BindingTypes type;      // This is for the type of selector used to set this binding.
  //String type;
  String datatype;        // Binding datatype. This one should be an xsd value. Does not require to be defined on the ontology TODO
  //String filetype;        // When datatype=anyURI and bindings is some url file. //FIXME: is this necessary? datatype could store this value

  public VariableBinding(){}

  @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
  public VariableBinding(
      @JsonProperty("variable") String variable,
      @JsonProperty("binding") List<String> binding,
      @JsonProperty("isArray") boolean isArray,
      @JsonProperty("type") String type,
      @JsonProperty("datatype") String datatype
    ) {
      this.variable = variable;
      this.binding = binding;
      this.isArray = isArray;
      this.datatype = datatype;
      this.type = VariableBinding.BindingTypes.valueOf(type);
  }

  public VariableBinding (String v, String b) {
	  variable = v;
    binding = new ArrayList<String>();
    binding.add(b);
    isArray = false;
  }

  public VariableBinding (String v, String b, String t) {
	  variable = v;
    binding = new ArrayList<String>();
    binding.add(b);
    datatype = t;
    isArray = false;
  }

  public VariableBinding (String v, List<String> b) {
	  variable = v;
    binding = b;
    isArray = true;
  }

  public VariableBinding (String v, List<String> b, String t) {
	  variable = v;
    binding = b;
    datatype = t;
    isArray = true;
  }
  
  public String getVariable() {
    return variable;
  }

  public void setVariable(String variable) {
    this.variable = variable;
  }

  public boolean getIsArray() {
    return isArray;
  }

  public void setIsArray (boolean b) {
    this.isArray = b;
  }

  public List<String> getBinding () {
    return this.binding;
  }

  public void setBinding (List<String> bindings) {
    this.binding = bindings;
  }

  @JsonIgnore
  public String getSingleBinding () {
    return isArray || binding.size() == 0 ? null : binding.get(0);
  }

  @JsonIgnore
  public void setSingleBinding (String binding) {
    if (!isArray) {
      this.binding = new ArrayList<String>();
      this.binding.add(binding);
    }
  }

  @JsonIgnore
  public List<String> getBindings () {
    return isArray ? this.binding : null;
  }

  @JsonIgnore
  public void setBindings (List<String> bindings) {
    if (isArray) {
      this.binding = bindings;
    }
  }
  
  public String getDatatype () {
    return datatype;
  }

  public void setDatatype (String t) {
    this.datatype = t;
  }

  /*public String getFiletype () {
    return filetype;
  }

  public void setFiletype (String t) {
    this.filetype = t;
  }*/

  //public BindingTypes getBindingType () {
  //  return bindingType;
  //}

  //public void setBindingType (BindingTypes t) {
  //  this.bindingType = t;
  //  this.type = t.name();
  //}

  public String getType () {
    return this.type.name();
  }

  public void setType (String t) {
    this.type = VariableBinding.BindingTypes.valueOf(t);
  }

  public String toString () {
    return "[" + variable + "|" + type + "|" + datatype + "]" + " = " 
        + (isArray && binding!=null ? String.join(",", binding) : (binding != null && binding.size() == 1 ? binding.get(0) : "null"));
  }

  public int compareTo (VariableBinding o) {
    return this.toString().compareTo(o.toString());
  }
}
